#define HEIGHT 100
#define WIDTH 100
#define NUM_AGENTS 50
#define MAX_ITERS 5000
#define VERBOSE true

// NOT EVERY APP
#define ADD_SPACE_REQ 1

// APP SPECIFIC
#define NUM_TASKS 16
#define TOTAL_DEMAND 80